name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

commands:
  market:
    description: Default command for this plugin.
    permission: market.use

permissions:
  market.use:
    description: Default permission for this plugin.
    default: true
  market.admin:
    description: Administrator permission for this plugin.
    default: op

depend: [Vault, MengDB, ProtocolLib]