name: NaturalMarket
version: ${project.version}
main: com.mengcraft.market.NaturalMarket

commands:
  market:
    description: Default command for this plugin.
    permission: market.use

permissions:
  market.use:
    description: Default permission for this plugin.
    default: true
  market.admin:
    description: Administrator permission for this plugin.
    default: op

depend: [Vault, MengDB, ProtocolLib]